const businesses = [
    {
      id: 1,
      name: 'Bansooriwala Alpha',
      image: '/Alpha/Bansooriwala.png',
      rating: 4.1,
      description: 'Food and Sweets',
      address: 'NeelKant Plaza, Alpha 1, Greater Noida',
      phone: '9650006934',
      category: 'Restaurant',
      location: 'Alpha, Greater Noida',
    },
    {
      id: 2,
      name: 'Pizza 47',
      image: '/beta/pizza47.png',
      rating: 3.8,
      description: 'Pizza DineIn and Home Delivery',
      address: '1st Floor, Beta Plaza, Greater Noida',
      phone: '7428110042',
      category: 'Restaurant',
      location: 'Beta, Greater Noida',
    },
    {
      id: 3,
      name: 'Akshara Hospital',
      image: '/Gamma/AksharaHospital.png',
      rating: 4.2,
      description: 'General, Physician, Orthopedic',
      address: 'Block J, Gammma, Greater Noida',
      phone: '7838460868',
      category: 'Healthcare',
      location: 'Gamma, Greater Noida',
    },
    {
        id: 4,
        name: 'EverGreen Sheets',
        image: '/Gamma/EvergreenSweets.png',
        rating: 3.9,
        description: 'Snacks and Sweets',
        address: 'Gamma-2 Market, Greater Noida',
        phone: '987654321',
        category: 'Restaurant',
        location: 'Gamma 2, Greater Noida',
      },
      {
        id: 5,
        name: 'Royale Bakers',
        image: '/Alpha/RoyaleBakers.png',
        rating: 4.4,
        description: 'Cakes and Pastries',
        address: 'Alpha 1, Greater Noida',
        phone: '9811779013',
        category: 'Bakery',
        location: 'Alpha, Greater Noida',
      },
      {
        id: 6,
        name: 'Axis Bank',
        image: '/Alpha/Axisbank.png',
        rating: 4.1,
        description: 'Private Commercial Bank',
        address: 'Alpha 1, Greater Noida',
        phone: '9873620008',
        category: 'Bank',
        location: 'Alpha, Greater Noida',
      },
      {
        id: 7,
        name: 'Brother Reapiring Center',
        image: '/Alpha/BrothersRepair.png',
        rating: 3.9,
        description: 'Services',
        address: 'Alpha 1 Commercial, Greater Noida',
        phone: '9630275117',
        category: 'Servies',
        location: 'Alpha, Greater Noida',
      },
      {
        id: 8,
        name: 'Makeup Studio',
        image: '/beta/MakeupStudio.png',
        rating: 4.6,
        description: 'Makeup and Beauty',
        address: 'Beta 2,Oxame mall, Greater Noida',
        phone: '8147944662',
        category: 'Saloon',
        location: 'Beta, Greater Noida',
      },
      {
        id: 9,
        name: 'TLH Dry Cleaner',
        image: '/beta/TLHdreycleaners.png',
        rating: 3.6,
        description: 'Dry Cleaners and Laundary',
        address: 'A-01, Beta-2, Greater Noida',
        phone: '7712860868',
        category: 'Services',
        location: 'Beta, Greater Noida',
      },
      {
        id: 10,
        name: 'Pari DryCleaners',
        image: '/Gamma/PariDrycleaner.png',
        rating: 4.2,
        description: 'Dry cleaner',
        address: 'Shop No. 40, Gammma-2, Greater Noida',
        phone: '7838460868',
        category: 'Services',
        location: 'Gamma, Greater Noida',
      },
      {
        id: 11,
        name: 'Poshak by Neha',
        image: '/Alpha/Poshak.png',
        rating: 5.0,
        description: 'Boutique and Design',
        address: 'Block C, Alpha 1, Greater Noida',
        phone: '9338463968',
        category: 'Services',
        location: 'Alpha, Greater Noida',
      },
      {
        id: 12,
        name: 'CZAR Unisex Saloon',
        image: '/Gamma/Czar.png',
        rating: 4.0,
        description: 'Hair and Makeup',
        address: 'Kadamba MArket, Gammma 1, Greater Noida',
        phone: '8077627741',
        category: 'Saloon',
        location: 'Gamma, Greater Noida',
      },
      {
        id: 13,
        name: 'Flexi Hospital',
        image: '/Gamma/Flexi.png',
        rating: 4.8,
        description: 'Mulit Super-Speciality Hospital',
        address: 'Block c, Gammma 1, Greater Noida',
        phone: '7835999666',
        category: 'Healthcare',
        location: 'Gamma, Greater Noida',
      },
      {
        id: 14,
        name: 'Prince Cantine',
        image: '/Gamma/PrinceCantine.png',
        rating: 4.0,
        description: 'Grocery Store',
        address: 'Block c, Gammma 1, Greater Noida',
        phone: '7835919436',
        category: 'Grocery',
        location: 'Gamma, Greater Noida',
      },
      {
        id: 15,
        name: 'A-one tiffin sefvices',
        image: '/beta/Aone.png',
        rating: 4.0,
        description: 'Tiffin Service porvider',
        address: 'Block E, Beta-1, Greater Noida',
        phone: '7835532423',
        category: 'Services',
        location: 'Beta, Greater Noida',
      },
      {
        id: 16,
        name: 'Inox Cinema',
        image: '/beta/InoxOmaxe.png',
        rating: 4.3,
        description: 'A cinema hall featuring Insignia, offering premium sound quality and exceptional services.',
        address: 'Block H, Beta-2, Greater Noida',
        phone: '8383874560',
        category: 'Entertainment',
        location: 'Beta, Greater Noida',
      },
      {
        id: 17,
        name: 'Aggarwal Departmental Store',
        image: '/Gamma/AggarwalRetail.png',
        rating: 4.5,
        description: 'Everyday essentials, fresh goods, and friendly service—your neighborhood convenience store.',
        address: 'Shop No. G1/1,Jagat farm,Gamma-1, Greater Noida',
        phone: '9034873077',
        category: 'Retail',
        location: 'Gamma, Greater Noida',
      },
  ];
  
  export default businesses;
  